Add files via upload
MayyarAA/studentplanner pull request #28
Opened 2020-11-08 00:06 UTC by hchugh08

1.Delete list view code added
 2.created the delete button

2020-11-08 02:26 UTC, ryab0 requested changes
Reading this left me a little confused, but maybe you can clarify at tomorrow's standup. The delete functionality should be included in listView.php should it not? Also was a little confused by line 22 and 40 - would both the create and delete not be triggered everytime as they have the same if statement?

2020-11-08 03:26 UTC, Rolo123y commented
Deleting a list should be in its own .php file which the listView.php can reference when you delete a task.

2020-11-08 08:25 UTC, gaurav613 commented
The option to delete a list would also be included in a modal(pop-up) on the listView page. Only the code for deleting can be moved to listView page.

2020-11-08 08:28 UTC, Rolo123y commented
> eting can be moved to listView page.

2020-11-08 08:30 UTC, Rolo123y commented
Deleting lists using popup is in the works in branch r2nasim-BoardViewUI.

2020-11-08 08:35 UTC, gaurav613 requested changes
I have left a few comments on this:

2020-11-08 08:35 UTC, gaurav613 commented on deletelistView.php
> +	//If the user submitted a new delete list request we run this code
Some modifications
- This block (line 40-48) can be moved to `listView.php`

- Change the variable inside the `$_POST` to be different from that of the create list call (e.g. `name_to_delete`) - this change should also be made in the form(`<input name = "">`) for the delete task

2020-11-08 08:35 UTC, gaurav613 commented on deletelistView.php
> +<div class="modal fade" id="createList" tabindex="-1" aria-labelledby="createList" aria-hidden="true">
- This block (line 100 - 119) can also be moved to `listView.php`

- Change the form input name to the `$_POST` variable name you changed above

2020-11-08 22:45 UTC, gaurav613 commented
Looks like you don't have the updated version of `listViews.php`. To fix this, pull the latest changes to your local main branch (`git pull origin main`), go to your branch(`git checkout <your-branch>`), then merge it with main (`git merge main`)

2020-11-09 02:32 UTC, ryab0 requested changes
@hchugh08 As discussed on our call:

- Requires a new button for Delete

- Modal should be opened by Delete button

Should use listID instead of listTitle to ensure it does not delete multiple lists with same name

2020-11-09 03:42 UTC, ryab0 approved these changes
Looks like you've made all the changes we discussed, nice work.

2020-11-09 06:54 UTC, gaurav613 commented
Closing now as this has been moved to #40 for cleaner commit trail/visibility of changes.

2020-11-09 06:54 UTC, closed without merging